- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Enable the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
- name: include common role
  include_role:
   name: common
  #  tasks_from: main
- name: copy the expense.conf configuration file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf  
  notify:
  - Restart Nginx  
