- name: removing the existing directory
  tags:
    - deployment
  ansible.builtin.file:
   path: "{{ APP_LOCATION }}" #for backend /app and for frontend is /usr/share/nginx/html
   state: absent

- name: ctreating  the  directory
  tags:
    - deployment
  ansible.builtin.file:
   path: "{{ APP_LOCATION }}" #for backend /app and for frontend is /usr/share/nginx/html
   state: directory
- name: download the required app related data
  tags:
    - deployment
  ansible.builtin.unarchive:
   src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
   dest: "{{ APP_LOCATION }}"
   remote_src: yes
 